apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: k8sgcr
  namespace: registry
spec:
  selector:
    matchLabels:
      app: k8sgcr
  serviceName: k8sgcr
  replicas: 1
  template:
    metadata:
      labels:
        app: k8sgcr
    spec:
      containers:
      - name: k8sgcr
        image: registry:2.8.1
        ports:
        - containerPort: 5000
          name: k8sgcr
        volumeMounts:
        - name: k8sgcr-data
          mountPath: /var/lib/registry
        - name: timezone
          mountPath: /etc/localtime
          readOnly: true
        - name: k8sgcr-cnf
          mountPath: /etc/docker/registry/config.yml
          subPath: config.yml
      volumes:
        - name: k8sgcr-cnf
          configMap:
            name: k8sgcr-cnf
        - name: timezone
          hostPath: 
            path: /usr/share/zoneinfo/Asia/Shanghai  
  volumeClaimTemplates:
  - metadata:
      name: k8sgcr-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 50Gi
