version: "3"
services:
  k8sgcr:
    image: "registry:2.8.3"
    container_name: "k8sgcr"
    restart: "always"
    volumes:
      - "/etc/localtime:/etc/localtime"
      - "./data:/var/lib/registry"
      - "./config.yml:/etc/docker/registry/config.yml"
    ports:
      - "5004:5000"
